first_msg = "<b>City:Talk</b>\n"
commands = [
	["start", """
Hello, this is a City:Talk.\n\
If you need help, please use command '/help'\n\
Thank you for using City:Talk :)\n\
    """],
	["stop", """
Stopping City:Talk Services... [OK]\
    """],
	["help", """
/ Command List /\n\
City:Talk {VERSION}\n\
- /start : Start City:Talk Services\n\
- /stop  : Stop City:Talk Services\n\
- /help  : Display command list\n\
- /status : Display server status\n\
- /ch [TEXT] : Send message to minecraft\n\
- /add [USERNAME] : Register whitelist to server\n\
- /remove [USERNAME] : Unregister whitelist to server\n\
- /rcon [COMMAND] : [ADMIN ONLY] Execute RCON\n\
- /map   : Display server's map\n\
    """],
	["status", """
/ Server Status /\n\
MINECRAFT ({SERVER_VERSION}) : {SERVER_STATUS} ({SERVER_USERS})\n\
    """],
    ["status_err", """
/ Server Status /\n\
ERR : Can't connect to server :(\n\
    """],
    ["add", """
/ Add whitelist /\n\
Successful! : {OUTPUT}\n\
    """],
    ["remove", """
/ Remove whitelist /\n\
Successful! : {OUTPUT}\n\
    """],
    ["remove_err", """
/ Remove whitelist /\n\
ADMIN ONLY\n\
    """],
    ["rcon", """
/ RCON /\n\
Successful! : {OUTPUT}\n\
    """],
    ["rcon_err", """
/ RCON /\n\
ADMIN ONLY\n\
    """],
    ["rcon_err2", """
/ RCON /\n\
ERR : Can't connect to server :(\n\
    """],
    ["chat", """
Chat! {OUTPUT}\n\
    """],
]


